import { Partner } from "@/lib/types";
import { Partners } from "./types";

export const PARTNERS: Partner[] = [
  {
    id: Partners.SwapX,
    website: "https://swapx.fi",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/34753.png",
    name: "SwapX",
    identifiers: ["swapx"],
  },
  {
    id: Partners.H2Finance,
    website: "https://h2finance.io",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/10545.png",
    name: "H2Finance",
    identifiers: ["h2finance"],
  },
  {
    id: Partners.SyncSwap,
    website: "https://syncswap.xyz",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/6813.png",
    name: "SyncSwap",
    identifiers: ["syncswap"],
  },
  {
    id: Partners.Quickswap,
    website: "https://quickswap.exchange/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/19966.png",
    name: "Quickswap",
    identifiers: ["quickswap", "quick"],
  },
  {
    id: Partners.Spookyswap,
    website: "https://spooky.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/1455.png",
    name: "Spookyswap",
    identifiers: ["spookyswap","spooky"],
  },
  {
    id: Partners.Lynex,
    website: "https://www.lynex.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/7957.png",
    name: "Lynex",
    identifiers: ["lynex"],
  },
  {
    id: Partners.Thena,
    website: "https://thena.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/5803.png",
    name: "Thena",
    identifiers: ["thena"],
  },
  {
    id: Partners.Arbidex,
    website: "https://arbidex.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/6506.png",
    name: "Arbidex",
    identifiers: ["arbidex"],
  },
  {
    id: Partners.Chronos,
    website: "https://chronos.exchange/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/24158.png",
    name: "Chronos",
    identifiers: ["chronos"],
  },
  {
    id: Partners.Baseswap,
    website: "https://baseswap.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/27764.png",
    name: "Baseswap",
    identifiers: ["baseswap"],
  },
  {
    id: Partners.Pancakeswap,
    website: "https://baseswap.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/7186.png",
    name: "PancakeSwap",
    identifiers: ["pancakeswap"],
  },
  {
    id: Partners.Sushiswap,
    website: "https://www.sushi.com",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/6758.png",
    name: "SushiSwap",
    identifiers: ["sushiswap"],
  },
  {
    id: Partners.Dragonswap,
    website: "https://dragonswap.app",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/10363.png",
    name: "DragonSwap",
    identifiers: ["dragonswap"],
  },
  {
    id: Partners.Retro,
    website: "https://retro.finance/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/7516.png",
    name: "Retro",
    identifiers: ["retro"],
  },
  {
    id: Partners.Fenix,
    website: "https://fenix.finance/",
    logo: "https://s2.coinmarketcap.com/static/img/exchanges/128x128/7516.png",
    name: "Fenix",
    identifiers: ["fenix"],
  },
  {
    id: Partners.TeaFi,
    website: "https://app.tea-fi.com/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/33924.png",
    name: "Teafi",
    identifiers: ["teaFi"],
  },
  {
    id: Partners.SparkDEX,
    website: "https://sparkdex.ai/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/36569.png",
    name: "SparkDEX",
    identifiers: ["sparkdex"],
  },

  {
    id: Partners.Blackhole,
    website: "https://blackhole.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/37396.png",
    name: "Blackhole",
    identifiers: ["blackhole"],
  },
  {
    id: Partners.Yowie,
    website: "https://mainnet.yowie.fi/#/?intro=true",
    logo: "https://ay3z1wftesmrvq3u.public.blob.vercel-storage.com/Token-Logo/TOKEN-LOGO.svg",
    name: "Yowie",
    identifiers: ["yowie"],
  },
  {
    id: Partners.Nami,
    website: "https://nami.xyz/",
    logo: "https://assets.coingecko.com/coins/images/28205/standard/Sei_Logo_-_Transparent.png",
    name: "Nami",
    identifiers: ["nami"],
  },
  {
    id: Partners.Kodiak,
    website: "https://kodiak.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/39166.png",
    name: "Kodiak",
    identifiers: ["kodiak"],
  },
  {
    id: Partners.Pangolin,
    website: "https://pangolin.fi/",
    logo: "https://s2.coinmarketcap.com/static/img/coins/128x128/8422.png",
    name: "Pangolin",
    identifiers: ["pangolin"],
  },
];
